version: '2'
services:
    jekyll:
        image: jekyll/jekyll:pages
        hostname: jekyll
        container_name: jekyll
        command: jekyll serve
        ports:
            - 4000:4000
        volumes:
            - ./web:/srv/jekyll