version: '2'
services:
    jekyll:
        image: jekyll/jekyll:pages
        hostname: jekyll
        container_name: jekyll
        command: jekyll build -w
        ports:
            - 4000:4000
        volumes:
            - ./web:/srv/jekyll
    nginx:
        image: nginx
        hostname: nginx
        container_name: nginx
        ports:
            - 4010:80
        volumes:
            - ./web/_site:/usr/share/nginx/html