jekyll:
    image: jekyll/jekyll:pages
    hostname: jekyll
    command: jekyll build -w
    ports:
        - 4000:4000
    volumes:
        - ./web:/srv/jekyll
nginx:
    image: nginx
    hostname: nginx
    ports:
        - 4010:80
    volumes:
        - ./web/_site:/usr/share/nginx/html